# Generated by Django 4.2 on 2023-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='Tree', max_length=100)),
                ('age', models.CharField(max_length=500)),
                ('variety', models.CharField(max_length=500)),
                ('soil_moisture', models.CharField(max_length=500)),
                ('temperature', models.CharField(max_length=500)),
                ('humidity', models.CharField(max_length=500)),
                ('light_exposure', models.CharField(max_length=500)),
                ('nutrient_levels', models.CharField(max_length=500)),
                ('pest_disease_outbreaks', models.CharField(max_length=500)),
                ('harvestTime', models.TimeField()),
                ('harvestDate', models.DateField(blank=True, null=True)),
                ('tree_image', models.ImageField(blank=True, null=True, upload_to='treeRecords')),
            ],
        ),
    ]
