# Generated by Django 4.2 on 2023-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='treeID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
